# -*- coding: utf-8 -*-
"""Chatbot_Simple.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cS5A4Cm50gnGHMHgBlWh8csNtEeARfBw
"""

import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

# load the data from the CSV file
data = pd.read_csv('/content/drive/MyDrive/data.csv') #Change path
df = data

# define a function to interact with the customer
def chatbot():
    print("Welcome to our store! How can I assist you today?")
    while True:
        user_input = input("Customer: ").lower()

        # exit condition
        if user_input == 'exit':
            print("Chatbot: Thank you for visiting us. Have a great day!")
            break

        # logic to find relevant products based on user input
        relevant_products = []
        for index, row in df.iterrows():
            # check if user input is found in any relevant columns of the current row
            if any(user_input in str(row[col]).lower() for col in ['Product Name', 'Category', 'About Product']):
                relevant_products.append(row)

        # sort relevant products by relevance
        relevant_products.sort(key=lambda x: sum(user_input in str(x[col]).lower() for col in ['Product Name', 'Category', 'About Product']), reverse=True)

        # top 5 limit
        relevant_products = relevant_products[:5]

        # recommending products to the customer
        if relevant_products:
            print("Chatbot: Here are up to 5 products you might be interested in:")
            for product in relevant_products:
                print(f"- Product Name: {product['Product Name']}")
                print(f"  Category: {product['Category']}")
                print(f"  Selling Price: ${product['Selling Price']}")
                print()  # Blank line for readability
        else:
            print("Chatbot: I'm sorry, we couldn't find any products matching your request.")

        # more dialogue

        print("Chatbot: Is there anything else I can assist you with? If not, just say 'exit'.")

# let the chatbot begin
chatbot()